CREATE TABLE `nominees` (
  `id` int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dob` date DEFAULT NULL,
  `age` int DEFAULT NULL,
  `nationality` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `gender` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `official_address` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `residential_address` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `field_of_specialization` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `phd_thesis_title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `joining_date` date DEFAULT NULL,
  `awards_details` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `contributions_to_science` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `contribution_social_imapact` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `technology_sectors` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lectures_delivered` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `foreign_assignments` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `research_summary` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `sci_journals_papers_number` int DEFAULT NULL,
  `citations_number` int DEFAULT NULL,
  `cumulative_impact_factor` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `h_index` int DEFAULT NULL,
  `patients` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `patiens` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `publication_file_url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `others` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `confirmation` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `consent` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `date` date DEFAULT NULL,
  `place` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nominator_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nominator_designation` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nominator_address` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `nominator_email` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `annexure_file_url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;